- id: '1670291009036'
  alias: Sunrise Automation
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: fan.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 768aba2888718844fe27b39f8fc7de36
  - service: fan.turn_on
    metadata: {}
    data: {}
    target:
      device_id: 768aba2888718844fe27b39f8fc7de36
  mode: single
- id: '1670291057332'
  alias: Sunset Automation
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: fan.set_percentage
    metadata: {}
    data:
      percentage: 10
    target:
      device_id: 768aba2888718844fe27b39f8fc7de36
  mode: single
