homeassistant:
  # Name of this Home Assistant instance
  name: Lisbon Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: Metric

  # Time zone
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon

  # Currency
  # Pick yours from here:
  # https://en.wikipedia.org/wiki/ISO_4217#Active_codes
  currency: EUR

  # URL Definition
  internal_url: !secret ha_internal_url
  external_url: !secret ha_external_url

  # Load packages
  packages: !include_dir_named packages/

  # Auth Providerrs
  auth_providers:
    - type: homeassistant
    # List of trusted networks, consisting of IP addresses or networks,
    # that are allowed to bypass password protection when accessing Home Assistant.
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        # - !secret external_ip
      allow_bypass_login: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5

### This is the section that loads with the default_config

dhcp:
energy:
frontend:
homeassistant_alerts:
image:
media_source:
my:
network:
person:
sun:
ssdp:
stream:
system_health:
webhook:
zeroconf:

### End of the default_config stuff

config:

alexa: !include alexa.yaml

discovery:

# updater:

light: !include light_groups.yaml

logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.ha_uptime
      - py.warnings

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover

  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.ha_uptime

logger: !include logger.yaml
recorder: !include recorder.yaml

# Text to speech
tts:
  - platform: google_translate

homekit: !include homekit.yaml
group: !include_dir_merge_named group
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script

template:
  - sensor: !include_dir_merge_list templates/sensor/

utility_meter: !include_dir_merge_list utility_meter/

powercalc:
