http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

alexa: !include alexa.yaml

light: !include light_groups.yaml

template:
  - sensor: !include_dir_merge_list templates/sensors/

sensor: !include_dir_merge_list sensors/

utility_meter: !include_dir_merge_list utility_meters/

powercalc:
