homeassistant:
  # Name of this Home Assistant instance
  name: Lisbon Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation

  # metric for metric, us_customary for US Customary
  unit_system: metric

  country: PT

  # Time zone
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon

  # Currency
  # Pick yours from here:
  # https://en.wikipedia.org/wiki/ISO_4217#Active_codes
  currency: EUR

  # URL Definition
  internal_url: !secret ha_internal_url
  external_url: !secret ha_external_url

  # Automation initial_state is on
  customize_domain:
    automation:
      initial_state: "on"

  # Load packages
  packages: !include_dir_named packages/

  # Auth Providers
  auth_providers:
    - type: homeassistant
    # List of trusted networks, consisting of IP addresses or networks,
    # that are allowed to bypass password protection when accessing Home Assistant.
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.2.0/24
      trusted_users:
        192.168.1.0/24:
          - !secret user_id_guest
          - !secret user_id_kiosk
        192.168.1.92: !secret user_id_kiosk
        192.168.2.0/24:
          - !secret user_id_guest
          - !secret user_id_kiosk
      allow_bypass_login: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 2400:cb00::/32
    - 2606:4700::/32
    - 2803:f800::/32
    - 2405:b500::/32
    - 2405:8100::/32
    - 2a06:98c0::/29
    - 2c0f:f248::/32
    - 172.30.33.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5

default_config:

config:

alexa: !include alexa.yaml

zha:
  zigpy_config:
    network:
      channel: 15
      channels: [15, 20, 25]
    ota:
      otau_directory: /config/zigpy_ota
      extra_providers:
        - type: ikea

# discovery:

light: !include_dir_merge_list light

logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.ha_uptime
      - py.warnings
      - sensor.em_energy_todaysumimport
      - sensor.em_energy_todaysumexport

history:

logger: !include logger.yaml
recorder: !include recorder.yaml

# Text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: "us-east-1"
    text_type: ssml
    voice: Joanna
    cache: true

homekit: !include homekit.yaml
group: !include_dir_merge_named group/
sensor: !include_dir_merge_list sensor/
automation: !include automations.yaml
automation mine: !include_dir_list automation/
scene: !include scenes.yaml
scene mine: !include_dir_list scene/
switch: !include_dir_merge_list switch/
script: !include scripts.yaml
script mine: !include_dir_merge_named script/

template:
  - sensor: !include_dir_merge_list templates/sensor/
  - trigger:
      - platform: time_pattern
        seconds: "/1"
    sensor: !include_dir_merge_list templates/seconds_sensor/

utility_meter: !include_dir_merge_named utility_meter/

influxdb: !include influxdb.yaml

input_number: !include_dir_merge_named input_number/
