- platform: group
  name: Dining Light
  unique_id: light.dining_light
  entities:
    - light.dining_a_light
    - light.dining_b_light
    - light.dining_c_light
- platform: group
  name: Saloon Lights
  unique_id: light.saloon_lights
  entities:
    - light.tv_light
    - light.living_light
    - light.dining_light
