- platform: group
  name: Dining Light
  unique_id: light.dining
  entities:
    - light.dining_a
    - light.dining_b
    - light.dining_c
- platform: group
  name: Saloon Lights
  unique_id: light.saloon
  entities:
    - light.tv
    - light.living
    - light.dining
