- platform: average
  name: "Average Temperature"
  entities:
    - sensor.azul_meter_temperature
    - sensor.bedroom_meter_temperature
- platform: average
  name: "Average Humidity"
  entities:
    - sensor.azul_meter_humidity
    - sensor.bedroom_meter_humidity
