- platform: average
  name: "Average Temperature"
  entities:
    - sensor.azul_temperature
    - sensor.bedroom_temperature
- platform: average
  name: "Average Humidity"
  entities:
    - sensor.azul_humidity
    - sensor.bedroom_humidity
