- platform: average
  name: "Average Temperature"
  entities:
    - sensor.azul_temperature
    - sensor.quarto_temperature
- platform: average
  name: "Average Humidity"
  entities:
    - sensor.azul_humidity
    - sensor.quarto_humidity
